### ISSUE TITLE
open badges backpack badge display issue

### ISSUE THREAD

**Issue by lamarve** [mozilla/openbadges-backpack#1006]
![cutoffbackpackimage](https://cloud.githubusercontent.com/assets/7081084/2540635/b21ab300-b5d5-11e3-9717-87bc47d9a66d.png)

I am a developer of testing and skill certification websites who after a couple of weeks of copy and paste in the validator finally got a badge baked, but when I went to view my badge in the backpack, the metadata descriptions were cut off in the viewer. Is this a bug in the badge viewer? Any help you can give me is appreciated....

Robert Evans

**Comment by mattdigitalme** [comment]
@auralon @ottonomy @lamarve Fixed post update 8/12/16?
