### ISSUE TITLE
Beta versions need deprecating

### ISSUE THREAD

**Issue by jadeforester** [mozilla/openbadges-backpack#1017]
The beta version of openbadges and backpack have been popping up a few times recently (http://beta.openbadges.org/backpack/login) 

Most recent was someone in Spain earning badges through an online course:

"I was sent this link - http://claim.openbadges.es/claim/EOI-CAW-2014-07/isabellamarco%40gmail.com - from an online course I´m doing to obtain my badge it automatically redirects me to the beta link."

![insignia](https://cloud.githubusercontent.com/assets/4763778/3118633/0b85a9c4-e73e-11e3-9278-fb5f8e07ced3.jpg)

The beta site needs to be sunsetted, correct?

**Comment by mattdigitalme** [comment]
@auralon close
