### ISSUE TITLE
User having issues signing up for Backpack

### ISSUE THREAD

**Issue by foresterjade** [mozilla/openbadges-backpack#1044]
From one of our community members:

"I have attempted to sign up to Mozilla Backpack, however after multiple times I have failed to do so because the page doesn't seem to be working.

I have attached screenshots of the process I take to try and sign up -  going to https://backpack.openbadges.org/backpack/login#, clicking 'log in or sign up', writing in my email address and clicking 'next' (as there is no actual 'sign up' button to press) only to be told that there is an error."

![screen_shot_2015-02-04_at_20_43_48](https://cloud.githubusercontent.com/assets/10866273/6060973/42bf76fe-ad3b-11e4-9c10-1f0ba08d69a1.jpg)

![screen shot 2015-02-04 at 20 44 06](https://cloud.githubusercontent.com/assets/10866273/6060975/45634f0c-ad3b-11e4-8994-2495e874c494.png)

Can someone please look into this? Is anyone else experiencing this error? I've also filed in the Persona Github here: https://github.com/mozilla/persona/issues/4213

Thanks.

**Comment by mattdigitalme** [comment]
@auralon Close
