### ISSUE TITLE
Problems sharing (some) public collections from Backpack

### ISSUE THREAD

**Issue by dpresant** [mozilla/openbadges-backpack#1052]
Hi:
Sunny suggested I post this here...

I just noticed that several of my public collections are returning an error when I attempt to share.

Here's an example:
http://backpack.openbadges.org/share/09bf106b3055d00c2a2f51074504ef08/
MESSAGE: no portfolio :(

Here's one that still works (multiple issuers):
http://backpack.openbadges.org/share/17f6462f49f45879c05cab3dd5d7c23a/

Here's a collection I just created with a single badge that currently works inside the collection above:
http://backpack.openbadges.org/share/undefined/
MESSAGE: Could not find group

What gives, do you think?

**Comment by mattdigitalme** [comment]
@dpresant Can you test this again for us Don since the update (8/12/16)

**Comment by dpresant** [comment]
I'm a bit stuck... tried migrating from Persona, did not receive the confirmation email, so I can't log in to Backpack.
Without logging in, I do notice that all those links still work the same.

**Comment by mattdigitalme** [comment]
@dpresant Did you sign in using the persona link, this then prompts you to enter an email address on Migration Screen 1 which should step you through the process.

Just testing again and seems to be up and working, let me know if you have the same issue again

M

**Comment by dpresant** [comment]
That's what I did - twice. 
No email returned, despite Step 2 message:
>> You have mail!
>> We have sent you an email with instructions for migrating your account.

**Comment by auralon** [comment]
What mail provider are you using?  Have you checked your spam inbox?

**Comment by dpresant** [comment]
I use fused.com. Nothing there. Checked Thunderbird and webmail interfaces. I normally have no issues with spam filtering.

**Comment by auralon** [comment]
OK, well we'll have to investigate this further. I'll see if we can get anything useful out of the logs from @cadecairos

**Comment by cadecairos** [comment]
The email provide likely doesn't support TLS connections on their email servers, so mailgun was refusing to send mail unencrypted... I've modified it to be opportunistic now, so it will send to servers that don't support encryption.

**Comment by mattdigitalme** [comment]
Thanks @cadecairos 

@dpresant Are you able to test again and let me know how you get on?

Thanks

**Comment by dpresant** [comment]
That did the trick, thanks.

This is no longer an issue:
_http://backpack.openbadges.org/share/09bf106b3055d00c2a2f51074504ef08/
MESSAGE: no portfolio :(_

Not sure what this was, I think I must have deleted it:
_http://backpack.openbadges.org/share/undefined/
MESSAGE: Could not find group_

I think you can kill this ticket...

**Comment by mattdigitalme** [comment]
Awesome news @dpresant 

@auralon can you close this one :)
