### ISSUE TITLE
Not able to upload badge to backpack due to case mismatch in email id

### ISSUE THREAD

**Issue by thunkWaltz** [mozilla/openbadges-backpack#1054]
I have been issued a badge which has my email id in capital letters, when I try to upload it to my backpack account created with same email id but small letters, it shows following error:
This badge was not issued to you! Contact your issuer. 

I tried to create another backpack account with email id in caps but it wont let me do so.

**Comment by ottonomy** [comment]
This is a significant issue. We were just talking today with a group of developers who are thinking about making some related changes, and there is a good liklihood of getting a fix for this by October, even though the fix will be fairly complex.  Thanks for posting.

**Comment by huloza** [comment]
Same problem with my account and entire university class, please fix it...! and thanks for the work!

**Comment by mattdigitalme** [comment]
@auralon something we should look in to

**Comment by auralon** [comment]
@mattdigitalme yeah, this is an issue that we should look into for the next phase of work.

**Comment by mattdigitalme** [comment]
Linked: https://github.com/mozilla/openbadges-backpack/issues/1130
