### ISSUE TITLE
beta.openbadges.org is not responding

### ISSUE THREAD

**Issue by atul-ebizon** [mozilla/openbadges-backpack#1057]
Hi,

We have few sites that uses https://beta.openbadges.org/ for accessing and issuing badge.

But now it is not responding, in console log it says "NetworkError: 503 Service Unavailable:...d server is at capacity - https://beta.openbadges.org/" , please see attached image.
![openbadging-not-responding](https://cloud.githubusercontent.com/assets/10229722/9629146/1bf0f92e-518e-11e5-9755-20d8d7dc335b.png)

Please let us know if we need to change the url.

**Comment by jbuck** [comment]
@atul-ebizon Hi there! I've just restored access to the backpack so it should be working for you now. If you'd like to know more I'll be posting updates in https://github.com/MozillaFoundation/mofo-devops/issues/171
