### ISSUE TITLE
The collections private/public does not produce the desired effect

### ISSUE THREAD

**Issue by tailot** [mozilla/openbadges-backpack#1062]
This collection is set private but the link is accessible to all:
https://backpack.openbadges.org/share/3f14d52e7f54fdb8a552ed35f2ef017d/

The configuration of the collection:
![image](https://cloud.githubusercontent.com/assets/330838/11016809/16c4a306-858c-11e5-9104-e2cc842c771a.png)

**Comment by tailot** [comment]
To reproduce it just set public or private on any collections

**Comment by baisong** [comment]
Hi @tailot, great question.

Maybe a better way to think about "public" collections is "discoverable" to other apps via the [Display API](https://github.com/mozilla/openbadges-backpack/wiki/Using-the-Displayer-API).

Here's a test account I own with 2 identical collections, [one public](https://backpack.openbadges.org/share/1c4f5da587bdf97def28ba48df90a03c/) and [one not](https://backpack.openbadges.org/share/b7f235e965ca3e6068cbf7741f198e30/):
![screenshot from 2016-01-07 16-26-21](https://cloud.githubusercontent.com/assets/228733/12186866/72986966-b55b-11e5-85dd-34b3082468f3.png)

So when I query the Displayer API to find out my earner collections, only the public one is returned:

![groups json](https://cloud.githubusercontent.com/assets/228733/12186872/8a9f2b44-b55b-11e5-860b-fb971f480854.png)

I'd be curious to better understand your use case?

**Comment by auralon** [comment]
@baisong, one use case would be, if a user shares the url with someone, whilst the collection is set to public, and then further down the line that user decides they want to hide that collection from people after all.  By setting it to private, the user expects others to not be able to see that collection... however, if someone accesses that shared url, they would still be able to see those badges.  It's confusing to the user, as most will not know that it "public" visibility only applies to displayer API functionality (many users will not know what an API is).  The terminology on the checkbox label could be changed, but as I just stated, any reference to APIs will not mean anything to some users.  With that consideration, it makes more sense to adjust the share page functionality, to hide it when a user sets a collection to private.
