### ISSUE TITLE
beta.openbadges.org/issuer.js returning 503 error.

### ISSUE THREAD

**Issue by xipxoom** [mozilla/openbadges-backpack#1066]
For at least the past several hours beta.openbadges.org has been returning a 503 error.  Chrome's developer console reports "Failed to load resource: the server responded with a status of 503 (Service Unavailable: Back-end server is at capacity)".

**Comment by ottonomy** [comment]
@simonwex -- this is interesting. I do know that some people are still using beta.openbadges.org in their implementations. I thought the domain was just pointing at backpack.openbadges.org now -- can you check to see if there's a server you can restart in @jbuck's absence?

@xipxoom we recommend you switch to backpack.openbadges.org, but in the meantime, we'll try to resolve the error you're encountering.

**Comment by xipxoom** [comment]
I greatly appreciate it.  I've passed your recommendation onto codeschool.  Thank you very much for your time.

**Comment by simonwex** [comment]
It looks like this was a forgotten dns when we moved our hosting environment. We've pointed the beta.openbadges.org dns to the prod instance.

**Comment by ottonomy** [comment]
Thanks, @simonwex. I've verified the fix, and now this issue may be safely closed.

**Comment by simonwex** [comment]
Thanks for verifying!
