### ISSUE TITLE
Broken Webmaker link in no-badges help text

### ISSUE THREAD

**Issue by ottonomy** [mozilla/openbadges-backpack#1068]
Actions pursuant to #676 added a link to https://badges.webmaker.org in https://github.com/mozilla/openbadges-backpack/blob/master/views/no-badges.html

The linked page no longer exists, and this help text should be updated.

Maybe update to the following:

``` html
<p>You can <a href="/backpack/add" class="add-openbadge">upload</a> directly any of the open badges you've earned.</p>
```

I will take it as an action item over the next month within the Badge Alliance to publish an updated list of quick badge earning opportunities that we can link from this page in the future. I'll update this issue as soon as this is complete.

**Comment by ottonomy** [comment]
The list of quick earning opportunities is not yet complete, but will be published within the coming weeks on openbadges.org

**Comment by ottonomy** [comment]
The Navigator badge would be an appropriate one to link to instead: http://toolness.github.io/hackasaurus-parable/navigator-badge/#

**Comment by mattdigitalme** [comment]
@ottonomy This has now been removed and updated with new text in the BP Update (8/12/16) 

@auralon can you close?
