### ISSUE TITLE
Text shadow on badge page looks really crappy (Fx Nightly / OS X)

### ISSUE THREAD

**Issue by djc** [mozilla/openbadges-backpack#1070]
On https://badges.mozilla.org/en-US/badges/claim/vpvacp, in the latest Firefox Nightly on OS X, a lot of the text looks kind of weird. This seems to be due to Bootstrap's text-shadow `text-shadow: 0 -1px 0 rgba(0,0,0,0.25);` property on `.badge`. I'm guessing maybe `.badge` is maybe applied more broadly than it should be here, but in any case it would be nice to neutralize this somehow.

**Comment by djc** [comment]
Still see it, for example on #detail .description.

**Comment by auralon** [comment]
This is for a different codebase! https://github.com/mozilla/badges.mozilla.org
