### ISSUE TITLE
503 Service Unavailable When Pushing Badge

### ISSUE THREAD

**Issue by jonathoy** [mozilla/openbadges-backpack#1080]
Hi,

I am trying to leverage the use of the backpack connect api with the intent on issuing badges to a user's backpack, but I seem to be encountering a 503 Service Unavailable error.

The response that I get after trying to issue the badge is as follows:

`"<!DOCTYPE html>\n    <html>\n    <head>\n      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n      <style type=\"text/css\">\n        html, body, iframe { margin: 0; padding: 0; height: 100%; }\n        iframe { display: block; width: 100%; border: none; }\n      </style>\n    <title>Application Error</title>\n    </head>\n    <body>\n      <iframe src=\"//s3.amazonaws.com/heroku_pages/error.html\">\n        <p>Application Error</p>\n      </iframe>\n    </body>\n    </html>"`

In the headers for my post request made to the /issue endpoint, I am including headers for the content type and my base64-encoded auth token. I have also validated my badge assertion using http://validator.openbadges.org/.

Any ideas as to what might be the issue here? It appears that the response comes from the server Cowboy, if that is any help.

I do not have my changes deployed to any environment currently, and have been testing this via a secure tunnel to my localhost Rails project using ngrok. If it is of benefit, however, I can provide my formed assertion or the details of the push request.

Thanks!

**Comment by mattdigitalme** [comment]
@auralon One to get in touch with for Connect API testing.

@jonathoy Do you want to join the [Backpack Developer Slack Channel](https://www.google.com/url?q=https%3A%2F%2Fbackpackng.slack.com%2Finvite%2FMTEyNDk3MDg1NjM4LTE0ODA2NzU0NzItODQ4MDBhOTE3ZQ&sa=D&sntz=1&usg=AFQjCNFNAJl0Dyf2rsl7s1-3RtUrTRYyiw) to get this worked through

**Comment by auralon** [comment]
@jonathoy if you could provide an example request (with headers), then I can investigate this further.

**Comment by mattdigitalme** [comment]
Closed - No update
