### ISSUE TITLE
Mailgun issues - migration emails not being received

### ISSUE THREAD

**Issue by mattdigitalme** [mozilla/openbadges-backpack#1113]
Hey @cadecairos We've had another few issues reported with the migration emails

One of them is the same again as yesterday: cblack@soton.ac.uk - could this be an educational filter issue? Any problems with this before?

Another is a reported issue from Twitter from a user: Ginny Franklin

Are you able to check the records at all for these accounts to see if there is anything we can report back to them?

Thanks (and apologies for the lack of technical details!)

M

**Comment by mattdigitalme** [comment]
As an update the other user got back to us - again a .ac.uk account

**Comment by cadecairos** [comment]
@mattdigitalme According to the logs, that first email address bounces on every send. It looks like it's undeliverable?

Other ac.uk emails that have failed show things like the domain being unresolveable and the email server IP address being blacklisted as a spammer.

**Comment by auralon** [comment]
So, I guess the question is, how do we resolve this, and get these recipients (who aren't spammers) to receive these emails?

**Comment by mattdigitalme** [comment]
@cadecairos @auralon Ok so at least we've identified there is an issue - is this something we need to resolve on our end, or is there something we need to tell the people who have been in touch to do on their end?

**Comment by mattdigitalme** [comment]
@cadecairos The user who is getting their emails bounced has asked if they can get any of these logs sent over so they can raise a support ticket at their end? Is this possible

**Comment by mattdigitalme** [comment]
Hey @cadecairos another one to check: luiggi.sansonetti@univ-paris3.fr Are we any closer to finding out what we might be able to do for these users? @auralon any more thoughts?

**Comment by auralon** [comment]
@mattdigitalme, not really.  I think @cadecairos has the most insight on this one.  If there is anything that needs addressing in the codebase, then I can take a look, but as far as I'm aware, that isn't the case.

**Comment by mattdigitalme** [comment]
@auralon Ok Sweet, over to you @cadecairos

**Comment by cadecairos** [comment]
> The user who is getting their emails bounced has asked if they can get any of these logs sent over so they can raise a support ticket at their end? Is this possible

@mattdigitalme The error message for that first user is "553 5.1.8 recipient <cblack@soton.ac.uk> denied #300 (sB8F45095545700700)"

**Comment by mattdigitalme** [comment]
Great thanks for this @cadecairos

**Comment by mattdigitalme** [comment]
Hey @cadecairos Are you able to give me an update (as you did with that last email address) on the state of these - so far they have tried migration a few times and received nothing:

* jelena.radlovic@skole.hr
* v.franklin@lboro.ac.uk
* luiggi.sansonetti@univ-paris3.fr
* luiggi.sansonetti@univ-rennes1.fr

Are we any closer to resolving why emails may not be getting through as not all of these are .ac.uk emails as we've previously had issues with. Be good to know if there is anything we could be telling end users to try 

Thanks
M

**Comment by cadecairos** [comment]
Since turning on mailgun, email bounce rates are at 0.16%.

I have a hunch the emails might be bouncing due to missing MX records on openbadges.org - I'll add them and we'll see if things improve.

**Comment by cadecairos** [comment]
> jelena.radlovic@skole.hr

"Domain of sender address .... does not exist" <- hoping to fix this by adding mx records for mg.openbadges.org

> v.franklin@lboro.ac.uk

"Unrouteable address Cannot verify sending domain" <- typically means the email domain is misspelled or the MX records of the receiving domain are incorrect and the mail can't be delivered.

> luiggi.sansonetti@univ-paris3.fr

"Domain of sender address ... does not exist" Same as first

> luiggi.sansonetti@univ-rennes1.fr

"Service unavailable; bad sender domain" Not sure what's going on here.

**Comment by auralon** [comment]
@cadecairos, 0.16% is pretty low, but hopefully with the MX changes we can reduce it even further! :+1:

**Comment by mattdigitalme** [comment]
@cadecairos This is great news on the percentage - with these MX record changes, I presume the users should attempt the migration process again, and hopefully will be successful?

**Comment by mattdigitalme** [comment]
Update - jelena.radlovic@skole.hr Successful migration - MX Record changes did the job! @cadecairos

**Comment by cadecairos** [comment]
![victory](http://media.giphy.com/media/x790itVk2bD9K/giphy.gif)

**Comment by mattdigitalme** [comment]
At @cadecairos Heard back from all parties mentioned in this thread - all successful! Moving to close this issue :) @auralon

**Comment by auralon** [comment]
Awesome! Nice work @cadecairos :)
