### ISSUE TITLE
Is this supposed to be broken or are you still in development?

### ISSUE THREAD

**Issue by eric-blue** [mozilla/openbadges-backpack#1119]
Getting that error from https://backpack.openbadges.org/backpack/add

![image](https://cloud.githubusercontent.com/assets/19786312/21373777/47164ce4-c6d6-11e6-961b-0420c5be7fbf.png)

**Comment by alanheppenstall** [comment]
It's not working for me either. I get a 303 response when trying to upload an image in that interface.

**Comment by mattdigitalme** [comment]
Hey @eric-blue & @alanheppenstall Can you let me know where the badge you are trying to upload originated from - and to what spec the badge has been baked. 

@cadecairos are you able to get us over the error logs so we can start taking a look with @auralon

**Comment by cadecairos** [comment]
Unfortunately, when this error occurs, the actual data about the error is lost (because it's only output if the log level is set to "debug").

Judging from the screenshot and by [reading the source](https://github.com/mozilla/openbadges-backpack/blob/master/controllers/backpack.js#L425-L429), this error seems to be related to the `tmpfile` variable. To the client, this would be the "userBadge" property that's uploaded.

side-note: it doesn't look like we're cleaning up the temporary files created by connect-multipart?

**Comment by alanheppenstall** [comment]
Hi @mattdigitalme - I'm getting a different error now.

<img width="810" alt="screen shot 2017-01-09 at 13 29 02" src="https://cloud.githubusercontent.com/assets/3407339/21768085/a6b7bba8-d66f-11e6-8268-9041bb6701f7.png">

**Comment by Starli0n** [comment]
I think you were like me, trying to upload a random image with the interface but you can only upload "bake" badge.

* Get the assertion url from the issuer you want to upload the badge
For my Git badge on Code School: https://www.codeschool.com/users/Starli0n/badges/121/assertion
* Check the url validation with http://validator.openbadges.org
* If the url is valid, go to the bakery with it: http://bakery.openbadges.org
* Save **Your Baked Badge**
* Upload it to the interface

It should work now :-)
For more details: [New Issuers: Give Yourself a Badge](https://github.com/mozilla/openbadges-backpack/wiki/New-Issuers:-Give-Yourself-a-Badge)

I needed to do it manually as the integration was not working from Code School.

**Comment by eric-blue** [comment]
Thanks for your answer! How might I find I get the assertion url however?

**Comment by Starli0n** [comment]
You are welcome :-)

For the assertion url, I inspected the requests sent from from Code School while trying to send a badge to my Backpack.
