### ISSUE TITLE
Failed to upload badger from issuer

### ISSUE THREAD

**Issue by Starli0n** [mozilla/openbadges-backpack#1126]
Hi,

- I tried to login from an issuer but the login popup stays when I click on Login (but still code 200 received)
- So I click on the cross to close it
- I try it again but this time, it seems that I am logged as I see my email
- I try the send my badge but I have the error (still with code 200):
```
You didn't add any open badges to your Backpack.
Visit your Backpack to manage and share your open badges. 
```

I tried on Code School and same goes with the [Navigator badge](http://toolness.github.io/hackasaurus-parable/navigator-badge/#)

I am a bit confused...

**Comment by jessemorton** [comment]
Also experiencing this issue

**Comment by auralon** [comment]
I've issued a fix for this, but I'm currently hit build errors.  Updating some dependencies due to security vulnerabilities has led to a few issues (whereby several tests now need to be rewritten).  I'm currently investigating which tests are affected.  Once I've ascertained that, then I'll deploy the changes to production so that the issuer functionality works again.  Bear with me!

**Comment by auralon** [comment]
OK, so the fix for this has been tested, staged, and ultimately deployed to the production Backpack.  Everything appears to be working as it should now.  Please let me know if you continue to experience this issue.  Thanks!

**Comment by Starli0n** [comment]
I tested on [navigator-badge](http://toolness.github.io/hackasaurus-parable/navigator-badge) login + badge sending

It works fine for me. Thanks a lot.

**Comment by ahripak** [comment]
I ran into this issue yesterday as well, but it persisted even with the downgrading to Express 4.x.

For me, it ended up being the `assertion.recipient` hash not matching the internal one that the Backpack would create—which really came down to differences in letter-casing on the email from the assertion and the email on the user record in the Backpack.

Essentially it's the same situation described by the OP, the message that would be returned was `You didn't add any open badges to your Backpack.` which seems to be a catchall for any unhandled errors where the underlying AJAX request returns an HTTP 200. I was going to submit a pull request to add verbose error handling in this case, but couldn't figure out a good way to do that short of refactoring the `badges-complete` listener in main.js

**Comment by auralon** [comment]
Hey @ahripak, how's it going?  Although it produces the same result, this issue was due to a different bug.  There is another issue #1130 that relates to email casing between the backpack and other systems.
