### ISSUE TITLE
When i have too many collections, since there isn't an automatically vertical > bottom scroll i cannot drag and drop badges unless i zoom out the webpage

### ISSUE THREAD

**Issue by will2294** [mozilla/openbadges-backpack#1129]
Normal size ( i can't add badges to the last collection):
![scroll_2](https://cloud.githubusercontent.com/assets/9334322/23699358/2450c922-03ef-11e7-8801-9547d3f3c01b.png)

Zoom in 33% ( only way of drag and dropping badges when i have multiple collections and i want to add a badge to the last one)
![scroll](https://cloud.githubusercontent.com/assets/9334322/23699324/f98be3a2-03ee-11e7-9c28-cf4e121045ca.png)

**Comment by cromatdragon** [comment]
I have the same issue. For me it's impossible add badges when I create new collections even with the zoom.

**Comment by cromatdragon** [comment]
A workaround for those insterested in this issue:

Use a developer tool like firebug and select the both divs (collections and badges) and add this simple css inline;

style="height: 500px; overflow-y:scroll;"
