### ISSUE TITLE
Login bug and collection display bug

### ISSUE THREAD

**Issue by ElricOfMelnibone** [mozilla/openbadges-backpack#1134]
When logging in, I get an error message: Error: Cannot enqueue Query after fatal error. at Protocol._validateEnqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:199:16) at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:135:13) at Connection.query (/app/node_modules/mysql/lib/Connection.js:208:25) at Function.find (/app/models/mysql-base.js:48:12) at Function.Model.findOne (/app/models/mysql-base.js:52:11) at /app/auth/passport.js:124:18 at process._tickCallback (node.js:458:13)
And badge collection retrieval fails and also gives an error message when following their links.

Everything was working yesterday morning.

**Comment by cromatdragon** [comment]
Same error here.

**Comment by ElricOfMelnibone** [comment]
Just tested this after an email from Matt, and it appears to be fixed. I'll close the issue.

Thanks!
