### ISSUE TITLE
api document github page t 404 

### ISSUE THREAD

**Issue by jefferysac** [mozilla/openbadges-backpack#1136]
https://github.com/mozilla/openbadges-backpack/blob/development/docs/apis/issuer_api.md

404

**Comment by auralon** [comment]
There is no `development` branch.  To access the resource you are looking for, you want

https://github.com/mozilla/openbadges-backpack/blob/master/docs/apis/issuer_api.md

May I ask, where did you find this link?  If it was in the openbadges-backpack documentation, then it will need correcting.

**Comment by jefferysac** [comment]
here https://github.com/mozilla/openbadges-backpack/wiki/Issuer-API

**Comment by auralon** [comment]
Thank you, I've now fixed that link.
