### ISSUE TITLE
There was an error uploading a badge

### ISSUE THREAD

**Issue by Veldkornet** [mozilla/openbadges-backpack#1137]
I'm trying to upload badges to my backpack via https://backpack.openbadges.org/backpack/add
But when ever I try add anything, it just tells me "There was an error uploading a badge"

![image](https://cloud.githubusercontent.com/assets/10297361/26250828/9d679526-3cab-11e7-95fe-4452e35b7e34.png)

**Comment by mattdigitalme** [comment]
Hey there @Veldkornet we've just pushed a new update to the Backpack this week - are you able to test this again and let me know how you get on 

Thanks

**Comment by mattdigitalme** [comment]
No update - closing
