### ISSUE TITLE
facebook sharing issue

### ISSUE THREAD

**Issue by mileginy** [mozilla/openbadges-backpack#1148]
There is a big empty space show in facebook for the openbadges link and no badge logo show.

![image](https://user-images.githubusercontent.com/25074507/28257279-16c0da4e-6afc-11e7-92b9-0c107f986249.png)

can you please check and rectify?

**Comment by mattdigitalme** [comment]
Hey @mileginy - I've just tested this using one of my collections to Facebook - the collection pulled through one of the badges as expected. 

Can you share me the URL of your public collection and also give me some OS and Browser details 

Thanks

M
![screen shot 2017-07-17 at 10 18 03](https://user-images.githubusercontent.com/11664863/28262096-bc4887be-6ad9-11e7-8a0e-6ffa34d04447.png)

**Comment by mileginy** [comment]
Hi @mattdigitalme, here my public collection url 
[https://backpack.openbadges.org/share/fd221761b41baab3019f59ad738f329d/ ](url)
My OS is Windows 10 and browser is Version 59.0.3071.115 (Official Build) (64-bit).

My colleague has tested few times, and the image appeared only 1 time, else it show blank. 

Thank you.

**Comment by mileginy** [comment]
Hi @mattdigitalme, are you able to simulate the problem ? If yes, may i know can you provide solution? Thank you.

**Comment by mattdigitalme** [comment]
I've not yet been able to replicate a FB share that doesn't pull through the image. Do you have any other badges you could add to a collection and share with FB that come from a different issuer? We can then see what happens there

Let me know if you need a badge issuing to test with and I can send you one over (if you send me your email address)

Thanks

Matt

**Comment by mattdigitalme** [comment]
No update - closing
