### ISSUE TITLE
Badge group title consistency

### ISSUE THREAD

**Issue by AndrewBarrettCa** [mozilla/openbadges-backpack#116]
The badge group title that appears on the home page (see http://dl.dropbox.com/u/10222256/badgeGroupTitleIssue.png) is different from the group detail page that appears when you select the share icon associated with the group (see http://beta.openbadges.org/share/e5062ac3143cbe99976beef540fe69f2 ).

If this is intentional, I think some cue is needed (e.g. input label) so the user knows that badge groups have a private title and a public title that can be different. I originally thought that my attempt to rename the group had not worked.

**Comment by mattdigitalme** [comment]
@auralon close?
