### ISSUE TITLE
First time badge claim and Persona set up UX improvement

### ISSUE THREAD

**Issue by threeqube** [mozilla/openbadges-backpack#271]
These suggestions come from NSTA who are integrating their Professional Development Scipack badges with the OBI. There are many in their community that are not too tech savvy so I thought these comments/suggestions were worth sharing. 
1. Step one: We ask our users to select a badge to  update to Mozilla (these will be only SciPack badges)
2. Step two: They are taken to Mozilla and asked to create an account (great), inputting an email
3. Step three: Email received with two URLs, ok (suggest putting completion of registration URL first, as this is action being requested to complete/validate Personal Persona account).
4. Step four: Appreciate the Personal “single sign-on” mechanism. At the end of this process,  a nice message says I can use Persona across the web—great, but I’m left hanging a little on the next step…maybe a prompt here, so I then went back to check my email to select the second link offered (openbadge.org)
5. Step five: From Open Badge link in email (first link listed) I was promoted with a new screen that suggested I consider P2PU (URL link) and given a “Browse” button to locate a “file” on my local HD.
   This is a little disconcerting from the UX, as I was attempting to upload an NSTA badge as the first action, then directed to create the Persona account (necessary action), and then in third/final step, I was not taken back to the original site where I was attempting to upload a badge.

We might suggest:
1. Most seamless suggestion: Might be cool if we pass along information from the site the user is coming from (NSTA in this instance), such that when they receive the email with the Persona registration link, the other link instead would take them back to the original site they came from (could be provided via code by issuer)….versus the Open Badge URL (user experience/logic little off here).
2. If this is already on the drawing board—great. Wonder if in the near term/immediate future,  could you provide some messaging in the email that directs the User to go back to the site where they were attempting to share the badge from into the Mozilla Open Badge after completing the Personal registration.

**Comment by mattdigitalme** [comment]
@auralon Close as Persona removed & replaced.
