### ISSUE TITLE
Backpacks need multiple email addresses

### ISSUE THREAD

**Issue by cmcavoy** [mozilla/openbadges-backpack#42]
Some badges might come from one email address, some badges come from others.  Just had this pointed out by a friend who received a badge on his UMich email, but wants to tie it to his Gmail based BrowserID backpack.  Logging it for a future fix (or maybe it already exists?)

**Comment by ypresto** [comment]
@cmcavoy 

It is sad to hear that because we're going to build web app on backpack API, and authentication is important to keep badges available even if user's email is changed.
Is pull request is welcomed?

**Comment by mattdigitalme** [comment]
https://github.com/mozilla/openbadges-backpack/pull/1156
