### ISSUE TITLE
Login inconsistency with uppercase email

### ISSUE THREAD

**Issue by adriangonz** [mozilla/openbadges-backpack#469]
Hi.

I'm a developer on a MOOC (Massive Open Online Course): http://aemprende.unimooc.com/. This MOOC is giving badges to the users which pass our assessments, but they have reported us an issue. Let's see an example:

I have an account on Mozilla Persona, BookuLibros@gmail.com (note the uppercase 'B' and 'L'), and I am registered on the MOOC as bookulibros@gmail.com (everything on lowercase). If the MOOC tries to award user with a badge it fails because the Persona's account was created with some uppercase letters and the badge is submitted to an account with everything on lowercase.

I've seen this issue also when you register an account on Persona with uppercase letters and try to login from beta.openbadges.org. The login windows freezes.

I think that an easy solution would be to manage the OpenBadges users with everything on lowercase.

For any contact, you can email me at kaseyo23@gmail.com or unimooc-tec@dlsi.ua.es.

**Comment by mattdigitalme** [comment]
Linked: https://github.com/mozilla/openbadges-backpack/issues/1130
