### ISSUE TITLE
Fix double login when accepting a badge on a site using persona

### ISSUE THREAD

**Issue by fmarier** [mozilla/openbadges-backpack#524]
(Title was: Backpack could use the issuer's Persona assertion to accept badges for a user)

This is a summary of an idea that @lloyd, @brianloveswords and I discussed today.

The basic idea is to take advantage of the fact that a user has already authenticated with Persona on the badge issuer site to avoid the need to log into the backpack just to receive a badge:
1. user logs into `issuer.example.com` with Persona assertion
2. issuer verifies assertion and logs the user in
3. issuer sends that same assertion to the backpack
4. backpack verifies the assertion with `audience=issuer.example.com`
5. backpack creates a limited session for that user, one that only allows badge uploads from `issuer.example.com`
6. issuer awards the user a badge and sends it to the backpack
7. the backpack presents a "do you accept this badge?" screen
8. that's it, the user goes back to the issuer site

Should the user want to manage badges, delete them, etc., he/she will need to properly log into the backpack. The limited session won't work for that.

Sending the original assertion over to the backpack creates a very strong trust relationship between the two sites because the backpack could turn around and use that same assertion to impersonate the user on `issuer.example.com`. We (Persona team) will be proposing a new API to address this use case.

**Comment by mattdigitalme** [comment]
@auralon what is the current situ with this in relation to passport.js?

**Comment by auralon** [comment]
@mattdigitalme sorted!
