### ISSUE TITLE
Badge revocation alert 

### ISSUE THREAD

**Issue by threeqube** [mozilla/openbadges-backpack#552]
![Screen Shot 2013-02-14 at 10 03 47 PM](https://f.cloud.github.com/assets/1424627/159398/6eeef94e-771d-11e2-9564-528808268a72.png)

**Comment by cutz** [comment]
[I recently discovered](https://groups.google.com/forum/#!topic/openbadges-dev/c8E9krPfucU) that assertions pushed to the backpack weren't removed or styled differently once revoked.  This lead me to believe I had incorrectly revoked the assertion, but it seems that this functionality just hasn't been tackled yet.   Are there any plans to pick this back up anytime soon?
