### ISSUE TITLE
Create landing page to manage My Open Badges

### ISSUE THREAD

**Issue by emgollie** [mozilla/openbadges-backpack#559]
@iamjessklein to mock up Backpack landing page as part of V1.0 deliverables (https://openbadges.etherpad.mozilla.org/obi-v1-0-UX-Jess). Emphasis is on a simple way for earners to view and manage their individual badges.

A slightly updated mockup from Ocupop will follow, but this gives a sense of page purpose:
![skitch](https://f.cloud.github.com/assets/1174853/161546/86ea83a4-7792-11e2-8a8b-da0fe6d218e0.png)

// cc @threeqube

**Comment by yy1105** [comment]
hi: do any one knwo about the open badge dimension? what dimension are they?
