### ISSUE TITLE
Backpack education: New earner interactions

### ISSUE THREAD

**Issue by emgollie** [mozilla/openbadges-backpack#578]
In addition to the sign-in page (https://github.com/mozilla/openbadges/issues/558), a few areas for explanation for people new to the Backpack include:

On random site side (per http://www.flickr.com/photos/jessicaklein/8091597178/in/photostream)
- Brief message for n00bs without a Backpack: "Bravo! You've can store & share the open badges you earn by creating a Backpack." ("Creating a Backpack" links to sign-in page on backpack.openbadges.org)

On Backpack side
- An About or How to Use Backpack page with clear instructions about 1) the value of organizing and sharing badges; 2) how to manage Collections and privacy settings; 3) how to use display badges and use Backpack Connect
- A Backpack tour video?
- Earner stories or real-life examples

// cc @threeqube @iamjessklein

**Comment by mattdigitalme** [comment]
@auralon close, this kind fo work has been implemented in new update to BP and OB sites respectively
