### ISSUE TITLE
Design error reporting throughout Backpack

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-backpack#610]
For now this is a bit of a placeholder. I think it involves:
- [ ] figuring out where errors occur that need to be reported back to users
- [ ] determining per page where errors occur how to display them effectively
- [ ] implementing the solution(s) across the pages

This should user-facing errors only. Any sort of instrumentation we want to collect error info isn't really included in this bug (although it might come out of the first checkbox).

**Comment by mattdigitalme** [comment]
@auralon Close as we now have error reporting messaging throughout new backpack NG
