### ISSUE TITLE
Create consistent header styles

### ISSUE THREAD

**Issue by stenington** [mozilla/openbadges-backpack#635]
We have a few approaches getting mixed together for how buttons/links in the header work in terms of visual styling. We should work out a consistent approach that gets used by default (i.e. looks good on the `/examples/badgetastic/test.html` page) and then add Backpack-specific tweaks on that if needed.

This means #600 can go through without proper styling, as that should happen by default when this issue is closed.

**Comment by mattdigitalme** [comment]
@auralon Close
