### ISSUE TITLE
Collection Name not making it to the edit/share page - still says "New Collection"

### ISSUE THREAD

**Issue by kayaelle** [mozilla/openbadges-backpack#738]
![Screen Shot 2013-03-08 at 1 33 53 PM](https://f.cloud.github.com/assets/206059/237749/3a04da24-881f-11e2-9855-01b1900ed6dc.png)

![Screen Shot 2013-03-08 at 1 34 08 PM](https://f.cloud.github.com/assets/206059/237754/75833514-881f-11e2-9609-57a1814b002d.png)

**Comment by mattdigitalme** [comment]
@auralon Fixed and close
