### ISSUE TITLE
Facebook and Twitter share buttons for backpack

### ISSUE THREAD

**Issue by davelester** [mozilla/openbadges-backpack#762]
The official Facebook share button was deprecated when the like button was introduced, so we'll have to make our own share button. There are lots of templates and examples out there, including this: http://www.titanui.com/3697-clean-classic-facebook-and-twitter-share-button-psd/

Could I have help creating share buttons for both Facebook and Twitter that are roughly the same dimensions as the 'disown this badge' button? If there isn't time, can someone point me to an image that we should use instead?

cc @iamjessklein @threeqube

**Comment by mattdigitalme** [comment]
@auralon close - LI, FB & T shares present and working
