### ISSUE TITLE
Create a collection area scrolls out of the view when there are several collections in the list

### ISSUE THREAD

**Issue by arasbm** [mozilla/openbadges-backpack#789]
![backpack_new_collection_scroll](https://f.cloud.github.com/assets/193687/284810/4b941f62-9200-11e2-8126-c3c479efab6b.png)
As you can see in the image the create collection view scrolls out of view. I would not say this is a bug but it makes the interaction for creating a new collection awkward. User has to scroll the area into the view (assuming they remember where it is) and then drag a badge into it. 

To fix this problem I suggest putting the create new collection area outside the list on top so it is always there and does not scroll down with the collections. Here is an image I made with gimp to show what I roughly mean, the visual design of it needs some work, but I think you get the idea.

![badge_backpack_create_new_collection_constant](https://f.cloud.github.com/assets/193687/284820/e187b4ac-9200-11e2-8e65-3b4a9564d003.png)

**Comment by mattdigitalme** [comment]
@auralon thoughts? Flip new collection to top of the list - Doable? Time/Work Load?

**Comment by auralon** [comment]
Yeah, we could flip this to the top, no probs.

**Comment by mattdigitalme** [comment]
@auralon Sweet

**Comment by mattdigitalme** [comment]
We've rebuilt the way collections work within the Backpack during the latest update 4.7.17 : https://github.com/mozilla/openbadges-backpack/commit/278704716df616ceb7abc778d8d50b1e9e4656a9
