### ISSUE TITLE
Collections failing to save properly with more than 3 or 4 badges

### ISSUE THREAD

**Issue by christensenep** [mozilla/openbadges-backpack#833]
I am experiencing an issue that prevents me from adding more than three (and occasionally four) badges to a collection.  This happens with all collections in my backpack at beta.openbadges.org, including newly created collections, and also including a second account I created to test if it was unique to my original account.  It does not happen at all with my own instance of the openbadges backpack, unfortunately, so I've been unable to debug the issue thoroughly.

I'm using a Windows 7 machine, and have tried multiple browsers.  Specifically:

Firefox - 19.0.2 & 20.0.1
IE - 10.0.9200.16540
Chrome - 26.0.1410.64 m

The response from the server upon attempting to drag a badge to the collection looks like:

{"status":"error","error":"there was an unknown error. it has been logged."}

The only source of this error appears to be here, during saving of a group: 

https://github.com/mozilla/openbadges/blob/development/controllers/group.js#L109

**Comment by mattdigitalme** [comment]
@christensenep Can you test this again post Backpack update 8/12/16 and let me know if there is still an issue

**Comment by mattdigitalme** [comment]
We've pushed another update to collections 4.7.17 (https://github.com/mozilla/openbadges-backpack/commit/278704716df616ceb7abc778d8d50b1e9e4656a9) will close this issue
