### ISSUE TITLE
Criteria link opens in popover frame instead of new window

### ISSUE THREAD

**Issue by digitalliteracyassessment** [mozilla/openbadges-backpack#991]
I have provided a link to criteria in my badge. When I test issuing it via the Issue API, the criteria URL appears as a link in the confirmation modal window. When users click on that link, it opens in the popover frame instead of opening a new window. Users report that they are "stuck" since the "X" close window icon disappears.

Is it possible to make the link have a target="_blank" so that it opens properly in a new window?

![screen shot 2014-01-14 at 7 52 38 pm](https://f.cloud.github.com/assets/5992397/1917033/31b861e2-7d88-11e3-883c-766f82c4c2ea.png)

![screen shot 2014-01-14 at 8 01 14 pm](https://f.cloud.github.com/assets/5992397/1917063/ee56e300-7d88-11e3-8a6b-8ea028d5af9c.png)

**Comment by jwbaker** [comment]
This does not appear to be resolved; I'm seeing the same behaviour in my application
